# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9570746e253b7f07e6f92ed84ae2d506991e771c848b05af9510b47a890ae1c1663e052f2801db6ccb4dd64d2036595d0ba147060b149428a4c84070e23c1b3

test:
  secret_key_base: 932666f2032cd94aff11590cefec6611a70c08f79d7b3447816ff5ef61dee539da7b8fad978ec2f3193520a0782285eea3c30239f8a9d169df4bd2d6ce6a4204

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
